### PR TITLE
More facts and tests 🐈

### PR DESCRIPTION
**Pull request by ekmartin**
Source: http://www.animalplanet.com/pets/cat-facts/ :cat: 
Added a test to make sure I wasn't adding duplicate tests, and made the use of const more consistent.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Fails on 0.12 and 0.10 because of `const` => https://travis-ci.org/vdemedes/cat-facts/jobs/104372340.

Could you revert it back to `var`?

**Comment by ekmartin** [comment]
Sorry, done!

**Comment by vadimdemedes** [comment]
Oh, forgot to mention, could you please squash last 2 commits into one?

**Comment by vadimdemedes** [comment]
AVA update commit should stay, only last 2

**Comment by ekmartin** [comment]
Squashed the facts and tests, and let the AVA commit stay, if that was what you meant.

**Comment by vadimdemedes** [comment]
Great stuff, thank you! 🐈

**Comment by ekmartin** [comment]
:cat2: :+1:

**Comment by vadimdemedes** [comment]
Published on npm as `cat-facts@1.0.2`.

**Pull request merged**
